<?php
/**
 * Stage 68.2.1: global ACF Pro settings.
 *
 * Editorial contract:
 * - no runtime text/url fallbacks;
 * - an empty admin value produces an empty runtime value;
 * - templates decide whether the corresponding element should be rendered;
 * - WooCommerce/system data must not be duplicated here.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Register the global settings page only when ACF Pro is available.
 */
function yabao_acf_register_global_settings_page(): void {
    if ( ! function_exists( 'acf_add_options_page' ) ) {
        return;
    }

    acf_add_options_page(
        array(
            'page_title' => 'Настройки сайта',
            'menu_title' => 'Настройки сайта',
            'menu_slug'  => 'yabao-global-settings',
            'capability' => 'edit_theme_options',
            'redirect'   => false,
            'position'   => 61,
            'icon_url'   => 'dashicons-admin-generic',
        )
    );
}
add_action( 'acf/init', 'yabao_acf_register_global_settings_page', 5 );

/**
 * Footer menus are separate so an administrator can manage each column
 * independently. No fallback menu is generated by the theme.
 */
function yabao_acf_register_global_menu_locations(): void {
    register_nav_menus(
        array(
            'footer_visit' => __( 'Подвал — посетить', 'ya-bao' ),
            'footer_info'  => __( 'Подвал — информация', 'ya-bao' ),
            'footer_legal' => __( 'Подвал — юридические ссылки', 'ya-bao' ),
        )
    );
}
add_action( 'after_setup_theme', 'yabao_acf_register_global_menu_locations', 20 );

/**
 * Read a global ACF value without inventing a replacement.
 *
 * @return mixed
 */
function yabao_site_setting( string $name ) {
    if ( ! function_exists( 'get_field' ) ) {
        return null;
    }

    return get_field( $name, 'option' );
}

/**
 * Read a plain-text global value.
 */
function yabao_site_text( string $name ): string {
    $value = yabao_site_setting( $name );

    if ( ! is_scalar( $value ) ) {
        return '';
    }

    return trim( wp_strip_all_tags( (string) $value ) );
}

/**
 * Read a URL global value.
 */
function yabao_site_url( string $name ): string {
    $value = yabao_site_text( $name );

    return '' !== $value ? esc_url_raw( $value ) : '';
}

/**
 * Read a plain-text subfield from a global ACF group.
 */
function yabao_site_group_text( string $group_name, string $field_name ): string {
    $group = yabao_site_setting( $group_name );

    if ( ! is_array( $group ) || ! isset( $group[ $field_name ] ) || ! is_scalar( $group[ $field_name ] ) ) {
        return '';
    }

    return trim( wp_strip_all_tags( (string) $group[ $field_name ] ) );
}

/**
 * Build a tel: URL from the configured public phone number.
 */
function yabao_site_phone_href(): string {
    $phone = yabao_site_text( 'phone' );

    if ( '' === $phone ) {
        return '';
    }

    $normalized = preg_replace( '/[^\d+]/u', '', $phone );

    return is_string( $normalized ) && '' !== $normalized
        ? 'tel:' . $normalized
        : '';
}

/**
 * Return valid social links for one placement.
 *
 * Incomplete repeater rows are ignored.
 */
function yabao_site_social_links( string $location ): array {
    $allowed_locations = array( 'header', 'mobile', 'footer' );

    if ( ! in_array( $location, $allowed_locations, true ) ) {
        return array();
    }

    $rows = yabao_site_setting( 'social_links' );

    if ( ! is_array( $rows ) ) {
        return array();
    }

    $result = array();

    foreach ( $rows as $row ) {
        if ( ! is_array( $row ) ) {
            continue;
        }

        $label = isset( $row['social_label'] ) && is_scalar( $row['social_label'] )
            ? trim( wp_strip_all_tags( (string) $row['social_label'] ) )
            : '';

        $url = isset( $row['social_url'] ) && is_scalar( $row['social_url'] )
            ? esc_url_raw( trim( (string) $row['social_url'] ) )
            : '';

        $icon_type = isset( $row['social_icon_type'] ) && is_scalar( $row['social_icon_type'] )
            ? sanitize_key( (string) $row['social_icon_type'] )
            : '';

        $locations = isset( $row['social_locations'] ) && is_array( $row['social_locations'] )
            ? array_map( 'sanitize_key', $row['social_locations'] )
            : array();

        $custom_icon = $row['social_custom_icon'] ?? 0;
        if ( is_array( $custom_icon ) && isset( $custom_icon['ID'] ) ) {
            $custom_icon = $custom_icon['ID'];
        }
        $custom_icon_id = absint( $custom_icon );

        if ( '' === $label || '' === $url || ! in_array( $location, $locations, true ) ) {
            continue;
        }

        if ( 'custom' === $icon_type && ! $custom_icon_id ) {
            continue;
        }

        if ( ! in_array( $icon_type, array( 'vk', 'telegram', 'custom' ), true ) ) {
            continue;
        }

        $result[] = array(
            'label'          => $label,
            'url'            => $url,
            'icon_type'      => $icon_type,
            'custom_icon_id' => $custom_icon_id,
        );
    }

    return $result;
}

/**
 * Render only the icon itself. No generic/fallback social icon is invented.
 */
function yabao_site_social_icon_html( array $social ): string {
    $icon_type = isset( $social['icon_type'] ) ? (string) $social['icon_type'] : '';

    if ( 'vk' === $icon_type && function_exists( 'yabao_asset_url' ) ) {
        return sprintf(
            '<img alt="" aria-hidden="true" decoding="async" height="48" src="%s" width="48">',
            esc_url( yabao_asset_url( 'icons/vk.svg' ) )
        );
    }

    if ( 'telegram' === $icon_type ) {
        return '<svg aria-hidden="true" viewBox="0 0 24 24"><path d="M20.7 4.3 3.9 10.8c-.9.4-.8 1.6.1 1.8l4.3 1.3 1.6 4.8c.3.9 1.5 1 1.9.2l2.3-4.1 4.1 3.3c.7.6 1.8.2 2-.7l2.4-11.7c.2-1-.8-1.9-1.9-1.4ZM9.5 13.4l8-6.1-6.3 7.4-.5 2.5-1.2-3.8Z" fill="currentColor"></path></svg>';
    }

    if ( 'custom' === $icon_type ) {
        $attachment_id = isset( $social['custom_icon_id'] ) ? absint( $social['custom_icon_id'] ) : 0;

        if ( $attachment_id ) {
            return (string) wp_get_attachment_image(
                $attachment_id,
                'thumbnail',
                false,
                array(
                    'alt'         => '',
                    'aria-hidden' => 'true',
                    'decoding'    => 'async',
                )
            );
        }
    }

    return '';
}